@file:OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)

package us.tractat.kuilt.warp.test

import kotlinx.coroutines.test.runTest
import us.tractat.kuilt.test.assertAll
import us.tractat.kuilt.warp.OpId
import us.tractat.kuilt.warp.TaskDescriptor
import us.tractat.kuilt.warp.TaskId
import us.tractat.kuilt.warp.opRegistryOf
import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * End-to-end proof of `@WarpOp` auto-registration (#925), running on **every** target:
 * [WarpOps] is generated by `:kuilt-warp-ksp` from the annotated [echo] declaration in
 * `WarpTestOps.kt` — there is no hand-written registry entry for it anywhere in this
 * module. Common metadata processing generates once; each target compiles the result,
 * so this commonTest suite passing on JVM/Android/iOS/macOS/wasmJs is the
 * cross-target evidence.
 */
class WarpOpAutoRegistrationTest {

    @Test
    fun generatedRegistrarCarriesTheAnnotatedOp() {
        assertEquals(setOf(OpId("echo")), WarpOps.opIds)
    }

    @Test
    fun annotatedOpIsRegisteredWithoutAManualEntry() {
        val registry = opRegistryOf(WarpOps)
        assertAll(
            { assertEquals(setOf(OpId("echo")), registry.registered) },
            { assertTrue(registry.resolve(OpId("echo")) === echo, "the registrar must install the annotated val itself") },
        )
    }

    @Test
    fun autoRegisteredOpRunsItsShuttleBody() = runTest {
        val op = assertNotNull(opRegistryOf(WarpOps).resolve(OpId("echo")))
        val input = byteArrayOf(4, 5, 6)
        assertContentEquals(input, op.invoke(input))
    }

    /**
     * The dispatch proof: a 3-node mesh whose registries are built *only* from the
     * generated registrar executes a task descriptor naming the auto-registered op,
     * and the result converges onto every peer's board.
     */
    @Test
    fun autoRegisteredOpIsDispatchableAcrossTheMesh() = warpSimTest(
        n = 3,
        registryFactory = { _, _ -> opRegistryOf(WarpOps) },
    ) { sim ->
        val task = TaskId("auto-registered-1")
        sim.node(0).enqueue(task, TaskDescriptor(op = OpId("echo"), args = task.value.encodeToByteArray()))

        sim.awaitResults(listOf(task))

        assertAll(
            { assertTrue(sim.peerIds.all { sim.nodes.getValue(it).results[task] != null }, "result must converge on every peer") },
            {
                val result = assertNotNull(sim.node(0).results[task])
                assertContentEquals(task.value.encodeToByteArray(), result.bytes, "echo must return its args")
            },
        )
    }
}
