package us.tractat.kuilt.warp.ksp

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class WarpOpsRendererTest {

    @Test
    fun rendersOneRegistrarObjectPerPackage() {
        val source = renderWarpOps(
            packageName = "com.example.search",
            ops = listOf(
                GeneratedOp(propertyName = "reverse", opId = "reverse"),
                GeneratedOp(propertyName = "scoreDoc", opId = "score"),
            ),
        )
        val expected = """
            |// Generated by kuilt-warp-ksp — do not edit.
            |package com.example.search
            |
            |import us.tractat.kuilt.warp.OpId
            |import us.tractat.kuilt.warp.OpRegistrar
            |import us.tractat.kuilt.warp.OpRegistry
            |
            |/**
            | * Registers every `@WarpOp`-annotated op declared in package `com.example.search`.
            | *
            | * Generated by the `kuilt-warp-ksp` symbol processor — do not edit, and do not
            | * register these ops by hand. Install with
            | * `us.tractat.kuilt.warp.opRegistryOf(WarpOps)` or `WarpOps.registerInto(registry)`.
            | */
            |public object WarpOps : OpRegistrar {
            |
            |    /** Every [OpId] this registrar installs. */
            |    public val opIds: Set<OpId> = setOf(
            |        OpId("reverse"),
            |        OpId("score"),
            |    )
            |
            |    override fun registerInto(registry: OpRegistry) {
            |        registry.register(OpId("reverse"), reverse)
            |        registry.register(OpId("score"), scoreDoc)
            |    }
            |}
            |""".trimMargin()
        assertEquals(expected, source)
    }

    @Test
    fun escapesOpIdStringLiterals() {
        val source = renderWarpOps(
            packageName = "com.example",
            ops = listOf(GeneratedOp(propertyName = "odd", opId = """a"b\c${'$'}d""")),
        )
        assertTrue("""OpId("a\"b\\c\${'$'}d")""" in source, "expected escaped literal in:\n$source")
    }

    @Test
    fun deriveOpIdPrefersExplicitId() {
        assertEquals("score", deriveOpId(explicitId = "score", propertyName = "scoreDoc"))
    }

    @Test
    fun deriveOpIdFallsBackToPropertyName() {
        assertEquals("reverse", deriveOpId(explicitId = "", propertyName = "reverse"))
    }
}
