package us.tractat.kuilt.webrtc.internal

import kotlinx.coroutines.flow.Flow
import us.tractat.kuilt.webrtc.IceConfig
import us.tractat.kuilt.webrtc.SignalingMessage

/**
 * Internal abstraction over `RTCPeerConnection` + `RTCDataChannel`.
 *
 * Lets unit tests substitute an in-memory paired implementation
 * without instantiating a real browser `RTCPeerConnection`. The real
 * impl lives in `BrowserRtcFacade`.
 *
 * Lifecycle:
 * 1. Construct via [RtcPeerConnectionFacadeFactory.create].
 * 2. Either call [createOffer] (host) or wait for a remote offer via
 *    [setRemoteDescription] then call [createAnswer] (joiner).
 * 3. Set the local description and ferry it to the peer via
 *    [SignalingChannel].
 * 4. Pump remote ICE candidates in via [addIceCandidate] as they
 *    arrive; observe local ICE candidates from [localIceCandidates].
 * 5. When [awaitDataChannelOpen] fires, the channel is ready.
 * 6. Send via [sendBytes]; receive via [incomingBytes].
 * 7. Call [close] to tear down.
 */
internal interface RtcPeerConnectionFacade {
    /** Local ICE candidates generated by the peer connection. */
    val localIceCandidates: Flow<SignalingMessage.IceCandidate>

    /**
     * Bytes received over the data channel. Backed by a single-use channel —
     * collect at most once (the browser impl closes it on `onclose`; a second
     * collector would fail). [WebRTCPeerLink] is the sole collector.
     */
    val incomingBytes: Flow<ByteArray>

    /** Suspends until the data channel transitions to `open`. */
    suspend fun awaitDataChannelOpen()

    /** Suspends until the connection enters a terminal failed state. */
    suspend fun awaitConnectionFailure(): Throwable

    /** Suspends until the remote closes the data channel cleanly. */
    suspend fun awaitDataChannelClose()

    suspend fun createOffer(): String // returns SDP

    suspend fun createAnswer(): String // returns SDP

    suspend fun setLocalDescription(
        sdp: String,
        type: SdpType,
    )

    suspend fun setRemoteDescription(
        sdp: String,
        type: SdpType,
    )

    suspend fun addIceCandidate(candidate: SignalingMessage.IceCandidate)

    suspend fun sendBytes(bytes: ByteArray)

    suspend fun close()
}

internal enum class SdpType { Offer, Answer }

internal interface RtcPeerConnectionFacadeFactory {
    /**
     * Create a facade configured with [iceConfig].
     *
     * [hostInitiated] controls whether this side creates a fresh data
     * channel ([true], host) or waits for the remote to attach one
     * ([false], joiner).
     */
    fun create(
        iceConfig: IceConfig,
        hostInitiated: Boolean,
    ): RtcPeerConnectionFacade
}
