package us.tractat.kuilt.warp.ksp

/**
 * One validated `@WarpOp` property, reduced to what code generation needs.
 *
 * @property propertyName The simple name of the annotated top-level `val` (same
 *   package as the generated registrar, so no import is required).
 * @property opId The resolved symbolic op id — the annotation's explicit id, or the
 *   property name when the annotation left it empty.
 */
internal data class GeneratedOp(val propertyName: String, val opId: String)

/**
 * Resolves the op id for an annotated property: [explicitId] wins; an empty
 * annotation id derives the wire name from [propertyName].
 */
internal fun deriveOpId(explicitId: String, propertyName: String): String =
    explicitId.ifEmpty { propertyName }

/**
 * Renders the generated `WarpOps` registrar object for [packageName].
 *
 * Output is `explicitApi()`-clean commonMain Kotlin: one `object WarpOps :
 * OpRegistrar` exposing the introspectable [opIds] set and the `registerInto`
 * implementation. [ops] must already be sorted deterministically by the caller —
 * the renderer emits them in the given order.
 */
internal fun renderWarpOps(packageName: String, ops: List<GeneratedOp>): String = buildString {
    appendLine("// Generated by kuilt-warp-ksp — do not edit.")
    appendLine("package $packageName")
    appendLine()
    appendLine("import us.tractat.kuilt.warp.OpId")
    appendLine("import us.tractat.kuilt.warp.OpRegistrar")
    appendLine("import us.tractat.kuilt.warp.OpRegistry")
    appendLine()
    appendLine("/**")
    appendLine(" * Registers every `@WarpOp`-annotated op declared in package `$packageName`.")
    appendLine(" *")
    appendLine(" * Generated by the `kuilt-warp-ksp` symbol processor — do not edit, and do not")
    appendLine(" * register these ops by hand. Install with")
    appendLine(" * `us.tractat.kuilt.warp.opRegistryOf(WarpOps)` or `WarpOps.registerInto(registry)`.")
    appendLine(" */")
    appendLine("public object WarpOps : OpRegistrar {")
    appendLine()
    appendLine("    /** Every [OpId] this registrar installs. */")
    appendLine("    public val opIds: Set<OpId> = setOf(")
    ops.forEach { appendLine("        OpId(${it.opId.asKotlinStringLiteral()}),") }
    appendLine("    )")
    appendLine()
    appendLine("    override fun registerInto(registry: OpRegistry) {")
    ops.forEach { appendLine("        registry.register(OpId(${it.opId.asKotlinStringLiteral()}), ${it.propertyName})") }
    appendLine("    }")
    appendLine("}")
}

/** Quotes this string as a Kotlin string literal, escaping `\`, `"`, and `$`. */
private fun String.asKotlinStringLiteral(): String = buildString {
    append('"')
    this@asKotlinStringLiteral.forEach { c ->
        when (c) {
            '\\' -> append("\\\\")
            '"' -> append("\\\"")
            '$' -> append("\\$")
            '\n' -> append("\\n")
            '\r' -> append("\\r")
            '\t' -> append("\\t")
            else -> append(c)
        }
    }
    append('"')
}
