import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

/**
 * Writes the canonical wasmJs Mocha/Karma timeout configuration into each module's
 * build directory. The Karma test runner discovers this via [KotlinKarma.useConfigDirectory],
 * which the `kuilt.kmp-library` convention plugin redirects to the build directory.
 *
 * The Gradle `useMocha { timeout }` DSL targets the wasmJs *node* task, not the
 * *browser* task — hence the `karma.config.d` file approach. Centralising it here
 * prevents per-module copies from drifting out of sync.
 */
abstract class GenerateKarmaTimeouts : DefaultTask() {

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun generate() {
        val file = outputFile.get().asFile
        file.parentFile.mkdirs()
        file.writeText(CONTENT)
    }

    companion object {
        /**
         * Content of the generated `timeouts.js`.
         *
         * - Raises Karma socket/activity timeouts: heavy tests (10k-item HLL accuracy,
         *   2048-bit SRA modular exponentiation) run as interpreted wasm with no JIT
         *   and block the browser's single JS thread for several seconds. The default
         *   ~2s ping timeout fires spuriously on slower CI runners.
         * - Raises the Mocha per-test limit for the same reason. `config.client` is
         *   mutated in place so the `client.args` array set by the Kotlin test runner
         *   is preserved.
         */
        val CONTENT: String = """
            |// Generated by kuilt.kmp-library convention plugin — do not edit by hand.
            |config.set({
            |    pingTimeout: 120000,
            |    browserNoActivityTimeout: 120000,
            |    browserDisconnectTimeout: 120000,
            |    browserDisconnectTolerance: 3,
            |    captureTimeout: 120000,
            |});
            |config.client = config.client || {};
            |config.client.mocha = config.client.mocha || {};
            |config.client.mocha.timeout = 120000;
        """.trimMargin()
    }
}
